_posts/2015-03-04-nodereinstall.md
The `nodereinstall` command completely re-installs node, npm and nvm. See the article on [Stack Overflow](http://stackoverflow.com/a/11178106/2083544) that got things started, and the [gist](https://gist.github.com/brock/5b1b70590e1171c4ab54) that led me to create this.
=> add nodereinstall command

_posts/2015-04-14-issh.md
Added package "is.sh". It's an alternative for test command.
=> Added package "is.sh"

_posts/2015-04-19-clock.md
=> fix markdown syntax

_posts/2015-05-05-shpec.md
Pulls in a slightly modified version of shpec's own README.
=> Add shpec package

index.md
Use setup.sh instead of old makefile
=> Update install command

_posts/2016-09-12-osxbootstrap.md
https://github.com/divio/osx-bootstrap
=> osxbootstrap

_posts/2017-02-06-tldr-bash-client.md
Once the bpkg install actually works, I will submit it as the recommended way to install at the tldr pages project: http://tldr-pages.github.io/
=> Added commandline option --version

_posts/2017-02-06-tldr-bash-client.md
Sorry, I understand now what went wrong. I hadn't created the separate branch after forking.
=> Tldr bash client

submit/index.md
This caught me and caused problems... Feel free to reword/reformat of course. I will now get off the master branch.
=> Added Fork instruction to submit page

_posts/2017-06-19-backup.md
=> Backup Utility

_config.yml
Fixed the lost link follow this.
=> Fix the lost link.

_posts/2017-06-28-rmate.md
Hi,
I would like to submit my rmate utility (for editing remote files in TextMate) to the bpkg repository.
=> Rmate -- remote TextMate utility

_posts/2019-05-07-warp.md
This tool makes file manipulation across terminals easy
=> Add warp to bpkg

_posts/2016-07-04-hr.md
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
=> Fix Markdown link markup

_posts/2021-05-06-chap.md
- rev'd chap version to 1.1.0
- added required bash version to chap post
- Improved documentation on chap post
- fixed bug with source control link on chap post
- added documentation on confirm_reset command
=> confirm_reset added, improved docs, bug fix on chap bpkg post

_posts/2021-03-30-passmenu.md, _posts/2021-05-06-chap.md
- Fixed bugs in chap post documentation
- Removed poorly thought out line loop commands
=> Updated chap post to reflect latest version

guidelines/index.md
Pending the completion of https://github.com/bpkg/bpkg/pull/124
=> Change mention of `package.json` to `bpkg.json`

guidelines/index.md
Documentation to accompany implementation of BPKG feature request noted in [BPKG issue #157](https://github.com/bpkg/bpkg/issues/157) and [BPKG code pull request #158](https://github.com/bpkg/bpkg/pull/158).
=> Added guideline for using `dependencies-dev` in package file.

assets/themes/the-program/css/_base.less, assets/themes/the-program/css/_mediaqueries.less, assets/themes/the-program/css/style.css, assets/themes/the-program/css/style.less
To correct issue #68, missing style rule provided.
=> Layout Full Height

assets/themes/the-program/css/_base.less, assets/themes/the-program/css/_mediaqueries.less, assets/themes/the-program/css/style.css, assets/themes/the-program/css/style.less
As mentioned in issue #70, suggested changes to for height were made.
=> Updated style rules to provide `min-height` values.

_posts/2023-07-07-protobuf-parser.md
Corrections to `protobuf-parser-bash` post.
=> Update protobuf-parser-bash post.

_posts/2024-02-06-echo-eval.md
Following the [submission guidelines](https://bpkg.sh/submit), this pull request publishes my [echo-eval](https://github.com/kj4ezj/echo-eval) project to the [bpkg website](https://bpkg.sh/packages/name).
Resolves `echo-eval` [issue 1](https://github.com/kj4ezj/echo-eval/issues/1).
=> Add kj4ezj/echo-eval

_posts/2024-06-18-drawercli.md
Dear bpkg Maintainers,
I hope this message finds you in good spirits. 
My name is Luis Adha, and I just submitted a Pull Request (PR) for my new package named "drawercli" to the bpkg/bpkg.github.io repository.
I am writing this letter to explain the reasons and benefits of this package and why I believe it will be a valuable addition to the bpkg community.
Brief Description of "drawercli"
"drawercli" is a CLI based tool designed for a different termux experience it will display a list of android applications that can be opened via touch on the terminal screen it will be installed on devices that have termux, it requires a special dependency on a third party application called "Termuxlauncher" you can be sure to install it safely on the phone, you can visit the official github page. This …
=> Subject: Request to Submit Package "drawercli" to the bpkg/bpkg.github.io Repository
